src/apps/fake_schemas_generation/urls.py
from django.urls import path

from . import views


app_name = "fake_schemas_generation"

urlpatterns = [
    path(
        "edit_schema/<slug:schema_url>",
        views.EditUserSchema.as_view(),
        name="edit_user_schema",
    ),
    path(
        "delete_schema/<slug:schema_url>",
        views.delete_user_schema,
        name="delete_user_schema",
    ),
    path(
        "generate/<uuid:dataset_id>", views.GenerateCSV.as_view(), name="generate_csv"
    ),
    path(
        "new_dataset/<slug:schema_url>",
        views.CreateDataSet.as_view(),
        name="add_dataset",
    ),
    path(
        "delete_dataset/<uuid:dataset_id>",
        views.delete_dataset_file,
        name="delete_dataset",
    ),
    path("<slug:schema_url>", views.UserSchema.as_view(), name="user_schema"),
    path("create_schema/", views.CreateUserSchema.as_view(), name="create_user_schema"),
    path("", views.UserSchemasList.as_view(), name="user_schemas_list"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.user_auth.urls", namespace="user_auth")),
    path(
        "",
        include(
            "apps.fake_schemas_generation.urls", namespace="fake_schemas_generation"
        ),
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = "apps.exceptions.views.handler_400"
handler403 = "apps.exceptions.views.handler_403"
handler404 = "apps.exceptions.views.handler_404"
handler500 = "apps.exceptions.views.handler_500"

src/apps/fake_schemas_generation/models/column.py
from uuid import uuid4

from django.db import models

from utils.data_types import RECORD_DATA_TYPES
from ..libs import constants


class Column(models.Model):
    """DB Table for storing column data: header, data type, data"""

    id = models.UUIDField(default=uuid4, primary_key=True, editable=False)
    header = models.CharField(
        max_length=constants.COLUMN_HEADER_MAX_LENGTH, verbose_name="Column header"
    )
    start_integer = models.PositiveSmallIntegerField(
        default=None, blank=True, null=True
    )
    end_integer = models.PositiveSmallIntegerField(default=None, blank=True, null=True)
    sentences = models.PositiveSmallIntegerField(default=None, blank=True, null=True)
    type = models.CharField(
        max_length=constants.COLUMN_TYPE_LENGTH,
        choices=RECORD_DATA_TYPES,
        verbose_name="Column data type",
        default="",
    )
    order = models.PositiveSmallIntegerField()
    schema = models.ForeignKey(
        to="fake_schemas_generation.Schema",
        on_delete=models.CASCADE,
        related_name="column",
    )

    class Meta:
        db_table = "schema_columns"
        ordering = ["schema", "order"]
        verbose_name = "Record data"
        verbose_name_plural = "Records data"
        unique_together = ["schema", "order"]

    def __str__(self) -> str:
        return f"{self.schema} | {self.header} | {self.get_type_display()}"

src/apps/fake_schemas_generation/models/data_set.py
from uuid import uuid4

from django.db import models

from utils.data_set import _get_folder_name


class DataSet(models.Model):
    """Is used to store generated datasets"""

    id = models.UUIDField(default=uuid4, primary_key=True, editable=False)
    csv_file = models.FileField(upload_to=_get_folder_name, editable=False)
    rows_quantity = models.IntegerField()
    generated_at = models.DateTimeField(
        auto_now_add=True
    )  # Date when DS has been created
    is_uploaded = models.BooleanField(default=False, editable=False)
    schema = models.ForeignKey(
        to="fake_schemas_generation.Schema",
        on_delete=models.CASCADE,
        related_name="dataset",
    )

    class Meta:
        db_table = "generated_csvs"
        verbose_name = "Dataset"
        verbose_name_plural = "Datasets"
        ordering = ["generated_at"]

    def __str__(self):
        return f"{self.schema} | {self.rows_quantity} {self.pk}"

    def delete(self, *args, **kwargs):
        self.csv_file.delete(save=False)  # Delete file directly from storage
        super().delete(*args, **kwargs)

src/apps/fake_schemas_generation/forms/column.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BaseInlineFormSet

from ..libs import constants
from ..models import Column


class ColumnForm(forms.ModelForm):
    class Meta:
        model = Column
        fields = [
            "header",
            "type",
            "order",
            "start_integer",
            "end_integer",
            "sentences",
        ]
        widgets = {
            "header": forms.TextInput(
                attrs={
                    "class": "form-control mt-3",
                    "placeholder": "Column header",
                    "required": True,
                }
            ),
            "type": forms.Select(
                attrs={
                    "class": "form-select mt-3",
                    "placeholder": "Choose column type",
                    "required": True,
                }
            ),
            "order": forms.NumberInput(
                attrs={
                    "class": "form-control mt-3",
                    "placeholder": "Order №",
                    "required": True,
                }
            ),
            "start_integer": forms.NumberInput(
                attrs={
                    "class": "form-control mt-3",
                    "placeholder": "From",
                }
            ),
            "end_integer": forms.NumberInput(
                attrs={
                    "class": "form-control mt-3",
                    "placeholder": "To",
                }
            ),
            "sentences": forms.NumberInput(
                attrs={
                    "class": "form-control mt-3",
                    "placeholder": "Sentences quantity",
                }
            ),
        }
        labels = {
            "header": "Column header",
            "type": "Column data type",
            "order": "Order №",
            "start_integer": "From",
            "end_integer": "To",
            "sentences": "Sentences quantity",
        }

    def clean_header(self):
        """Validating row header length. Miminal length is set in constants"""
        header = self.cleaned_data["header"]
        header_min_length = constants.COLUMN_HEADER_MIN_LENGTH
        if len(header) < header_min_length:
            raise ValidationError(
                f"Column header can not be less than {header_min_length} symbols"
            )
        return header

    def clean_type(self):
        """To prevent make sure that user has changed the default data type"""
        column_type = self.cleaned_data["type"]
        if column_type == "df":
            raise ValidationError("Please choose data type")
        return column_type


class BaseColumnFormSet(BaseInlineFormSet):
    """FormSet to update the order of Settings in a Machine"""

    def clean(self):
        """Checks if there are no two Settings with the same order."""
        if any(self.errors):
            return
        orders = []
        sorted_form = sorted(self.forms, key=lambda f: f.cleaned_data["order"])
        for idx, form in enumerate(sorted_form, 1):
            if form.cleaned_data:
                order = form.cleaned_data["order"]
                column_type = form.cleaned_data["type"]
                if column_type == "i":  # Integer field
                    """Validating required fields for this field type"""
                    start_integer = form.cleaned_data.get("start_integer")
                    end_integer = form.cleaned_data.get("end_integer")
                    if start_integer is None:
                        form.add_error("start_integer", "Enter a number")
                    if end_integer is None:
                        form.add_error("end_integer", "Enter a number")
                    if start_integer and end_integer:
                        if start_integer > end_integer:
                            form.add_error("start_integer", "Can't be less than To")

                if column_type == "t":  # Text field
                    """Checking sentences field"""
                    sentences = form.cleaned_data.get("sentences")
                    if sentences is None:
                        form.add_error("sentences", "Enter a number")
                if idx != order:
                    form.add_error("order", "Ordering must be continuous numbering")

                if order in orders:
                    form.add_error("order", "The order of each column must be unique")
                else:
                    orders.append(order)

src/apps/fake_schemas_generation/forms/schema.py
from django import forms
from django.core.exceptions import ValidationError

from ..libs import constants
from ..models import Schema, Column
from .column import ColumnForm, BaseColumnFormSet


class SchemaForm(forms.ModelForm):
    class Meta:
        model = Schema
        fields = ["title", "separator", "quotes"]
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "form-control mt-3", "placeholder": "Schema title"}
            ),
            "separator": forms.Select(
                attrs={"class": "form-select mt-3", "placeholder": "Column separator"}
            ),
            "quotes": forms.Select(
                attrs={"class": "form-select mt-3", "placeholder": "String quotes"}
            ),
        }
        labels = {
            "title": "Schema title",
            "separator": "Column separator",
            "quotes": "String quotes",
        }

    def clean_title(self):
        """Used for validating minimum length of title which is set in constants"""
        title = self.cleaned_data["title"]
        if len(title) < constants.SCHEMA_TITLE_MIN_LENGTH:
            raise ValidationError(
                f"Title length can not be less than {constants.SCHEMA_TITLE_MIN_LENGTH} symbols"
            )
        return title


ColumnFormSet = forms.inlineformset_factory(
    Schema, Column, ColumnForm, extra=1, formset=BaseColumnFormSet
)

src/apps/fake_schemas_generation/views/dataset.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic, View

from .. import services, models


class CreateDataSet(LoginRequiredMixin, View):
    def post(self, request, schema_url: str):
        try:
            rows_quantity = int(request.POST.get("rows quantity"))
        except ValueError:
            raise 404

        schema = services.get_user_schema(request.user, schema_url)
        services.create_dataset(schema, rows_quantity)
        messages.success(request, "Dataset has been created successfully")
        return redirect("fake_schemas_generation:user_schema", schema_url=schema_url)


class GenerateCSV(LoginRequiredMixin, View):
    """Generating CSV file by given dataset ID"""

    def post(self, request, dataset_id):
        dataset = services.get_dataset(dataset_id)
        services.generate_csv(dataset)

        return JsonResponse(data={"message": "Success", "status": 201}, status=200)


@login_required
def delete_dataset_file(request, dataset_id):
    """"""
    dataset = services.get_dataset(dataset_id)
    dataset.delete()
    messages.success(request, "Generated file was deleted")
    return JsonResponse(data={"message": "Success", "status": 204}, status=200)

src/apps/fake_schemas_generation/views/schema.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import generic, View

from utils.pagination import PaginationMixin
from .. import forms, services


class CreateUserSchema(LoginRequiredMixin, View):
    """View for creating new user schema with form and inline formset"""

    def get(self, request):
        context = {"form": forms.SchemaForm(), "column_formset": forms.ColumnFormSet()}
        return render(request, "fake_schemas_generation/create_schema.html", context)

    def post(self, request):
        """Processing POST request from form and formset.
        Update formset forms and saving form and formset instances to DB"""
        form_data: dict = request.POST.copy()
        form = forms.SchemaForm(form_data)
        button = form_data.get("button")
        if button == "submit":  # Submit form
            if form.is_valid():
                schema = form.save(commit=False)
                schema.user = request.user
                formset = forms.ColumnFormSet(form_data, instance=schema)
                if formset.is_valid():
                    schema.save()
                    formset.save()
                    return redirect("fake_schemas_generation:user_schemas_list")

                return render(
                    request,
                    "fake_schemas_generation/create_schema.html",
                    {"form": form, "column_formset": formset},
                )
        formset = services.get_updated_formset(
            form_data=form_data, formset=forms.ColumnFormSet, button_data=button
        )
        return render(
            request,
            "fake_schemas_generation/create_schema.html",
            {"form": form, "column_formset": formset},
        )


class EditUserSchema(LoginRequiredMixin, View):
    """View for editing new user schema with form and inline formset"""

    def get(self, request, schema_url: str):
        schema = services.get_user_schema(request.user, schema_url)
        form = forms.SchemaForm(instance=schema)
        formset = forms.ColumnFormSet(instance=schema)
        context = {"schema_url": schema_url, "form": form, "column_formset": formset}
        return render(request, "fake_schemas_generation/edit_schema.html", context)

    def post(self, request, schema_url):
        """Processing POST request from form and formset.
        Update formset forms and saving form and formset instances to DB"""
        schema = services.get_user_schema(request.user, schema_url)
        form_data: dict = request.POST.copy()
        form = forms.SchemaForm(form_data, instance=schema)
        button = form_data.get("button")
        if button == "submit":  # Submit form
            if form.is_valid():
                schema = form.save(commit=False)
                schema.user = request.user
                formset = forms.ColumnFormSet(form_data, instance=schema)
                if formset.is_valid():
                    schema.save()
                    formset.save()
                    return redirect("fake_schemas_generation:user_schemas_list")

                return render(
                    request,
                    "fake_schemas_generation/edit_schema.html",
                    {"schema_url": schema_url, "form": form, "column_formset": formset},
                )
        formset = services.get_updated_formset(
            form_data=form_data,
            formset=forms.ColumnFormSet,
            button_data=button,
            instance=schema,
        )

        return render(
            request,
            "fake_schemas_generation/edit_schema.html",
            {"schema_url": schema_url, "form": form, "column_formset": formset},
        )


class UserSchemasList(LoginRequiredMixin, PaginationMixin, generic.ListView):
    template_name = "fake_schemas_generation/schemas_list.html"
    context_object_name = "schemas"
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(
            **kwargs,
            title="Schemas list",
        )
        context.update(**self.get_pages(page_obj=context["page_obj"]))
        return context

    def get_queryset(self):
        return services.get_user_schemas(self.request.user)


class UserSchema(LoginRequiredMixin, PaginationMixin, generic.ListView):
    """Displaying schema columns and schemas datasets"""

    template_name = "fake_schemas_generation/schema_detail.html"
    slug_url_kwarg = "schema_url"
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(
            **kwargs,
            schema=self.schema,
            title=self.schema.title,
        )
        context.update(**self.get_pages(page_obj=context["page_obj"]))
        return context

    def get_queryset(self):
        self.schema = services.get_user_schema(
            self.request.user, schema_url=self.kwargs["schema_url"]
        )
        return services.get_schema_datasets(self.schema)


@login_required
def delete_user_schema(request, schema_url):
    schema = services.get_user_schema(request.user, schema_url)
    schema.delete()
    messages.success(request, "Schema has been deleted successfully")
    return redirect("fake_schemas_generation:user_schemas_list")

src/apps/fake_schemas_generation/templates/fake_schemas_generation/_form.html
{# Form #}

{% for field in form %}

  <div class="row">
    <div class="col-sm-3 col-md-3 col-lg-3"></div>
    <div class="col-sm-6 col-md-6 col-lg-6">
      <div class="form-floating">
        {{ field }}
        <label for="{{ field.label }}">{{ field.label }}</label>
        {% for error in field.errors %}
          <p class="mt-3 text-danger">{{ error }}</p>
        {% endfor %}
      </div>
    </div>
    <div class="col-sm-3 col-md-3 col-lg-3"></div>
  </div>

{% endfor %}

  {% csrf_token %}

{# Buttons #}
<div class="row mt-3">
  <div class="col-sm-3 col-md-3 col-lg-3"></div>
  <div class="col-sm-6 col-md-6 col-lg-6">
    <div class="row">
      <div class="col-sm-4 col-md-4 col-lg-4">
        <button type="reset" class="btn btn-danger">Reset</button>
      </div>
      <div class="col-sm-4 col-md-4 col-lg-4"></div>
      <div class="col-sm-4 col-md-4 col-lg-4">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>

    </div>
  </div>
  <div class="col-sm-3 col-md-3 col-lg-3"></div>
</div>
<div class="row">

</div>

src/apps/fake_schemas_generation/templates/fake_schemas_generation/create_schema.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <form id="schema-form-container" action="{% url 'fake_schemas_generation:create_user_schema' %}" method="post">
    <div class="row text-center mt-3">
      <h3 class="fw-lighter">Creating new schema</h3>
      <div class="col-sm-2 col-md-2 col-lg-2"></div>
      <div class="col-sm-8 col-md-8 col-lg-8">

        {# Schema title #}
        <div class="form-floating">
          {{ form.title }}
          <label for="{{ form.title.label }}">{{ form.title.label }}</label>
          {% for error in form.title.errors %}
            <p class="mt-3 text-danger">{{ error }}</p>
          {% endfor %}
        </div>

        {# Schema extra parameters #}
        <div class="row">

          {# Schema column separator #}
          <div class="col-sm-5 col-md-5 col-lg-5">
            <div class="form-floating">
              {{ form.separator }}
              <label for="{{ form.separator.label }}">{{ form.separator.label }}</label>
              {% for error in form.separator.errors %}
                <p class="mt-3 text-danger">{{ error }}</p>
              {% endfor %}
            </div>
          </div>

          <div class="col-sm-1 col-md-1 col-lg-1"></div>
          <div class="col-sm-1 col-md-1 col-lg-1"></div>

          {# Schema string quotes #}
          <div class="col-sm-5 col-md-5 col-lg-5">
            <div class="form-floating">
              {{ form.quotes }}
              <label for="{{ form.quotes.label }}">{{ form.quotes.label }}</label>
              {% for error in form.quotes.errors %}
                <p class="mt-3 text-danger">{{ error }}</p>
              {% endfor %}
            </div>
          </div>
        </div>

        {# Column parameters #}
        <div class="row text-center mt-3">
          <h3>Column parameters</h3>

          {{ column_formset.management_form }}
          {% for form in column_formset %}
            <div class="column-form">
              {% include 'fake_schemas_generation/_column_form.html' %}
            </div>
          {% endfor %}

        </div>

      </div>
      <div class="col-sm-2 col-md-2 col-lg-2"></div>
    </div>

  </form>
{% endblock %}

src/apps/fake_schemas_generation/templates/fake_schemas_generation/edit_schema.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <form id="schema-form-container" action="{% url 'fake_schemas_generation:edit_user_schema' schema_url=schema_url %}"
        method="post">
    <div class="row text-center mt-3">
      <h3 class="fw-lighter">Creating new schema</h3>
      <div class="col-sm-2 col-md-2 col-lg-2"></div>
      <div class="col-sm-8 col-md-8 col-lg-8">

        {# Schema title #}
        <div class="form-floating">
          {{ form.title }}
          <label for="{{ form.title.label }}">{{ form.title.label }}</label>
          {% for error in form.title.errors %}
            <p class="mt-3 text-danger">{{ error }}</p>
          {% endfor %}
        </div>

        {# Schema extra parameters #}
        <div class="row">

          {# Schema column separator #}
          <div class="col-sm-5 col-md-5 col-lg-5">
            <div class="form-floating">
              {{ form.separator }}
              <label for="{{ form.separator.label }}">{{ form.separator.label }}</label>
              {% for error in form.separator.errors %}
                <p class="mt-3 text-danger">{{ error }}</p>
              {% endfor %}
            </div>
          </div>

          <div class="col-sm-1 col-md-1 col-lg-1"></div>
          <div class="col-sm-1 col-md-1 col-lg-1"></div>

          {# Schema string quotes #}
          <div class="col-sm-5 col-md-5 col-lg-5">
            <div class="form-floating">
              {{ form.quotes }}
              <label for="{{ form.quotes.label }}">{{ form.quotes.label }}</label>
              {% for error in form.quotes.errors %}
                <p class="mt-3 text-danger">{{ error }}</p>
              {% endfor %}
            </div>
          </div>
        </div>

        {# Column parameters #}
        <div class="row text-center mt-3">
          <h3>Column parameters</h3>

          {{ column_formset.management_form }}
          {% for form in column_formset %}
            <div class="column-form">
              {% include 'fake_schemas_generation/_column_form.html' %}
              {% for hidden in form.hidden_fields %}
                {{ hidden }}
              {% endfor %}
            </div>
          {% endfor %}

        </div>

      </div>
      <div class="col-sm-2 col-md-2 col-lg-2"></div>
    </div>

  </form>

{% endblock %}

src/apps/fake_schemas_generation/templates/fake_schemas_generation/schema_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="row text-center">
    <div class="col-sm-2 col-md-2 col-lg-2"></div>

    <div class="col-sm-8 col-md-8 col-lg-8">
      <h3 class="fw-light mt-4 mb-4">{{ schema.title }}</h3>
      {% if messages %}
        {% for message in messages %}
          <p class="text-success">{{ message }}</p>
        {% endfor %}
      {% endif %}
      <div class="row text-center">

        <div class="col-sm-7 col-md-7 col-lg-7 text-center">
          <h4 class="fw-light mb-4">Schema columns</h4>
          <table class="table table-striped">
            <thead>
            <tr>
              <th scope="col" class="fw-light">#</th>
              <th scope="col" class="fw-light">Column header</th>
              <th scope="col" class="fw-light">Column type</th>
            </tr>
            </thead>
            <tbody>
            {% for column in schema.column.all %}
              <tr>
                <td>
                  {{ column.order }}
                </td>

                <td class="align-end">
                  {{ column.header }}
                </td>

                <td>
                  {% with column.get_type_display as column_type %}
                    {% if column_type == "Text" %}
                      {{ column_type }}({{ column.sentences }} sentences)
                    {% elif column_type == "Integer"%}
                      {{ column_type }}(From {{ column.start_integer }} to {{ column.end_integer }})
                    {% else %}
                      {{ column_type }}
                    {% endif %}
                  {% endwith %}
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="col-sm-5 col-md-5 col-lg-5">
          <div class="row">
            <div class="col-sm-3 col-md-3 col-lg-3"><h4 class="fw-light mb-4">Datasets</h4></div>

            <div class="col-sm-9 col-md-9 col-lg-9">
              <form method="post" action="{% url 'fake_schemas_generation:add_dataset' schema_url=schema.slug %}"
                    id="form_dataset">
                <div class="row">
                  <div class="col-sm-6 col-md-6 col-lg-6">
                    <div class="form-floating">
                      <input type="number" name="rows quantity" class="form-control" placeholder="Rows quantity"
                             required
                             min="0"
                             id="rows quantity">
                      <label for="rows quantity">Rows quantity</label>
                    </div>
                  </div>
                  <div class="col-sm-6 col-md-6 col-lg-6">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success text-white mt-3">Add new</button>
                  </div>
                </div>
              </form>

            </div>

          </div>
          <table class="table table-striped">
            <thead>
            <tr>
              <th scope="col" class="fw-light">Rows</th>
              <th scope="col" class="fw-light">Created at</th>
              <th scope="col" class="fw-light">Status</th>
              <th scope="col" class="fw-light">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for dataset in page_obj %}
              <tr>
                <td>
                  {{ dataset.rows_quantity }}
                </td>
                <td class="align-end">
                  {{ dataset.generated_at|date:"d E, Y" }}

                </td>
                <td>
                  {% if dataset.is_uploaded %}
                    <div class="badge bg-success dataset{{ forloop.counter }} text-black  fw-light">
                    Generated
                  {% else %}
                    <div class="badge bg-warning dataset{{ forloop.counter }} text-black  fw-light">
                    Not generated
                  {% endif %}
                  </div>
                </td>
                <td>
                  <div class="row">
                    {% if dataset.is_uploaded %}
                      <div class="col-sm-6 col-md-6 col-l-6">
                        <a href="{{ dataset.csv_file.url }}" class="btn btn-sm btn-outline-success">Download</a>
                      </div>
                      <div class="col-sm-6 col-md-6 col-l-6">
                        <button type="button" class="btn btn-sm text-dark btn-outline-danger"
                                data-bs-toggle="modal" data-bs-target="#delete_file_modal{{ forloop.counter }}"
                                id="modal_button{{ forloop.counter }}">
                          Delete
                        </button>
                      </div>
                    {% else %}
                      <div class="col-sm-3 col-md-3 col-lg-3"></div>
                      <div class="col-sm-6 col-md-6 col-lg-6">
                        <form action="{% url 'fake_schemas_generation:generate_csv' dataset_id=dataset.pk %}"
                              id="generate_csv{{ forloop.counter }}" method="post">
                          {% csrf_token %}
                          <button type="submit" id="button{{ forloop.counter }}"
                                  class="btn btn-outline-warning text-dark fw-bold btn-sm">Generate
                          </button>
                        </form>
                      </div>
                      <div class="col-sm-3 col-md-3 col-lg-3"></div>
                    {% endif %}
                  </div>
                </td>
              </tr>
              {% include 'fake_schemas_generation/modals/delete_dataset.html' %}

            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>

    </div>

    <div class="col-sm-2 col-md-2 col-lg-2"></div>

  </div>
{% endblock %}

{% block custom_js %}
  <script src="{% static 'js/datasets.js' %}"></script>
{% endblock %}

src/apps/fake_schemas_generation/templates/fake_schemas_generation/schemas_list.html
{% extends 'base.html' %}


{% block content %}
  <div class="row text-center">
    <div class="col-sm-2 col-md-2 col-lg-2"></div>

    <div class="col-sm-8 col-md-8 col-lg-8">
      <h3 class="fw-light mt-4 mb-4">This is all your schemas, {{ user.username }}</h3>
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col" class="fw-light">#</th>
          <th scope="col" class="fw-light">Schema</th>
          <th scope="col" class="fw-light">Modified</th>
          <th scope="col" class="fw-light">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for schema in schemas %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td class="align-end"><a href="{% url 'fake_schemas_generation:user_schema' schema_url=schema.slug %}"
                                     class="text-decoration-none text-dark fw-bolder">{{ schema.title }}</a>
            </td>
            <td>{{ schema.edited_at|date:"d E, Y H:i" }}</td>
            <td>
              <a href="{% url 'fake_schemas_generation:edit_user_schema' schema_url=schema.slug %}"
                 class="btn btn-outline-success text-dark me-5"
              >Edit schema</a>
              <button type="button" class="btn text-dark btn-outline-danger"
                      data-bs-toggle="modal" data-bs-target="#delete_schema_modal"
              >Delete schema
              </button>
            </td>
          </tr>
          {% include 'fake_schemas_generation/modals/delete_schema.html' %}
        {% endfor %}
        </tbody>
      </table>

    </div>

    <div class="col-sm-2 col-md-2 col-lg-2"></div>

  </div>

{% endblock %}