src/apps/fake_schemas_generation/urls.py
from django.urls import path

from . import views


app_name = "fake_schemas_generation"

urlpatterns = [
    path(
        "edit_schema/<slug:schema_url>",
        views.EditUserSchema.as_view(),
        name="edit_user_schema",
    ),
    path(
        "delete_schema/<slug:schema_url>",
        views.delete_user_schema,
        name="delete_user_schema",
    ),
    path(
        "generate/<uuid:dataset_id>", views.GenerateCSV.as_view(), name="generate_csv"
    ),
    path(
        "new_dataset/<slug:schema_url>",
        views.CreateDataSet.as_view(),
        name="add_dataset",
    ),
    path(
        "delete_dataset/<uuid:dataset_id>",
        views.delete_dataset_file,
        name="delete_dataset",
    ),
    path("<slug:schema_url>", views.UserSchema.as_view(), name="user_schema"),
    path("create_schema/", views.CreateUserSchema.as_view(), name="create_user_schema"),
    path("", views.UserSchemasList.as_view(), name="user_schemas_list"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.user_auth.urls", namespace="user_auth")),
    path(
        "",
        include(
            "apps.fake_schemas_generation.urls", namespace="fake_schemas_generation"
        ),
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = "apps.exceptions.views.handler_400"
handler403 = "apps.exceptions.views.handler_403"
handler404 = "apps.exceptions.views.handler_404"
handler500 = "apps.exceptions.views.handler_500"

src/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    {% if title %}
      {{ title }}
    {% else %}
      Schemas generator
    {% endif %}
  </title>
  {% load static %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body class="bg bg-body-secondary">

{# header #}

<header class="bd-header sticky-top bg-dark py-3 d-flex align-items-stretch border-bottom border-dark">

  <div class="container-fluid">

    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

      <ul class="nav col-sm-auto col-md-auto col-lg-auto me-sm-auto me-md-auto me-lg-auto mb-2 mb-md-0">
        {% if user.is_authenticated %}
          <li>
            <a href="{% url 'fake_schemas_generation:user_schemas_list' %}" class="btn btn-outline-info ms-2 me-3"
            >Schemas list
            </a>
          </li>
          <li>
            <a href="{% url 'fake_schemas_generation:create_user_schema' %}" class="btn btn-outline-info ms-2 me-3"
            >New schema
            </a>
          </li>
        {% endif %}

      </ul>

      <div class="text-end">
        {% if user.is_authenticated %}
          <button type="button" class="btn btn-outline-light me-2"
                  data-bs-toggle="modal" data-bs-target="#logout_modal">
            Logout
          </button>
        {% else %}
          <button type="button" class="btn btn-outline-light me-2"
                  data-bs-toggle="modal" data-bs-target="#login_modal">
            Sign-in
          </button>
        {% endif %}
      </div>
    </div>
  </div>


</header>
{% include 'user_auth/modals/sign_in.html' %}
{% include 'user_auth/modals/sign_out.html' %}


<div class="container-fluid justify-content-center">
  {% block content %}
  {% endblock content %}
</div>

{% if page_obj.has_other_pages %}
<nav class="container-fluid align-content-center pb-5 sticky-bottom">
  <ul class="pagination d-lg-flex justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link bg-body-tertiary fw-light text-decoration-none text-dark"
           href="?page={{ page_obj.previous_page_number }}">Previous</a>
      </li>
    {% endif %}
    {% for page in pages %}
        <li class="page-item">
          {% if page == page_obj.number %}
            <a class="page-link disabled fw-bolder" href="?page={{ page }}">{{ page }}</a>
          {% else %}
            <a class="page-link bg-body-tertiary fw-light text-decoration-none text-dark"
               href="?page={{ page }}">{{ page }}</a>
        </li>
      {% endif %}

    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link bg-body-tertiary fw-light text-decoration-none text-dark"
                               href="?page={{ page_obj.next_page_number }}">Next</a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

<div class="mb-5"></div>
<footer class="footer mt-sm-5 mt-md-5 mt-lg-5 py-3 bg-dark fixed-bottom">
  <div class="container text-center">
    <span class="text-white">
      &copy; 2023 Mykyta Khylko
      <a href="https://github.com/Vaipik/PLANEKS_Django_test/" class="text-white text-decoration-none fw-lighter"
      >Github
      </a>
    </span>
  </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.3.min.js"
        integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous">
</script>
<script src="{% static 'js/sign_in.js' %}"></script>
{% block custom_js %}
{% endblock %}
</body>
</html>