src/apps/user_auth/urls.py
from django.urls import path

from . import views


app_name = "user_auth"

urlpatterns = [
    path("sign_in/", views.SignInView.as_view(), name="login"),
    path("sign_up/", views.SignUpView.as_view(), name="registration"),
    path("sign_out/", views.SignOutView.as_view(), name="logout"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.user_auth.urls", namespace="user_auth")),
    path(
        "",
        include(
            "apps.fake_schemas_generation.urls", namespace="fake_schemas_generation"
        ),
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = "apps.exceptions.views.handler_400"
handler403 = "apps.exceptions.views.handler_403"
handler404 = "apps.exceptions.views.handler_404"
handler500 = "apps.exceptions.views.handler_500"

src/apps/user_auth/models.py
from django.db import models

# Create your models here.

src/apps/user_auth/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .libs import constants


User = get_user_model()


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        min_length=constants.USER_MIN_LEGNTH,
        max_length=constants.USER_MAX_LEGNTH,
        label="Enter username",
        widget=forms.TextInput(
            attrs={"class": "form-control mt-3", "placeholder": "username"}
        ),
    )
    password1 = forms.CharField(
        max_length=constants.PASSWORD_MAX_LENGTH,
        label="Enter your password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control mt-3", "placeholder": "Enter password"}
        ),
    )
    password2 = forms.CharField(
        max_length=constants.PASSWORD_MAX_LENGTH,
        label="Repeat your password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control mt-3", "placeholder": "Repeat password"}
        ),
    )

    class Meta:
        model = User
        fields = ["username"]


class SignInForm(AuthenticationForm):
    username = forms.CharField(
        min_length=constants.USER_MIN_LEGNTH,
        max_length=constants.USER_MAX_LEGNTH,
        label="Enter username",
        widget=forms.TextInput(
            attrs={
                "class": "form-control mt-3",
                "placeholder": "username",  # required to prettify view of form
            }
        ),
    )
    password = forms.CharField(
        max_length=constants.PASSWORD_MAX_LENGTH,
        label="Enter password",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control mt-3",
                "placeholder": "password",  # required to prettify view of form
            }
        ),
    )

src/apps/user_auth/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View, generic

from . import forms


class SignUpView(generic.CreateView):
    """Registraion view"""

    template_name = "user_auth/sign_up.html"
    form_class = forms.SignUpForm

    def get_success_url(self):
        login(self.request, self.object)  # self.object -> created user
        return reverse_lazy("fake_schemas_generation:user_schemas_list")


class SignInView(View):
    """Accepts AJAX request from sign in modal form and login user."""

    def post(self, request):
        username = request.POST.get("username")
        password = request.POST.get("password")
        if username and password:
            user = authenticate(username=username, password=password)  # If user exists
            if user:
                login(request, user)
                return JsonResponse(
                    data={
                        "message": "Logged in",
                        "status": 200,
                        "url": redirect(
                            "fake_schemas_generation:user_schemas_list"
                        ).url,
                    },
                    status=200,
                )

        return JsonResponse(
            data={"message": "Invalid credentials", "status": 400}, status=200
        )


class SignOutView(LoginRequiredMixin, View):
    """Accepts POST request form sign out modal form and signing out user.
    Afterwards redirecting user to registartion page"""

    def post(self, request):
        logout(request)
        return redirect("user_auth:registration")

src/apps/user_auth/templates/user_auth/modals/sign_in.html
<div class="modal fade" id="login_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Sign in form</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="alert alert-danger d-none" role="alert">
      </div>

      <form method="POST" action="{% url 'user_auth:login' %}" id="login_form">
        <div class="modal-body">

          {% for field in login_ajax %}
            <div class="row">
              <div class="col">
                <div class="form-floating text-center">
                  {{ field }}
                  <label for="{{ field.name }}">{{ field.label }}</label>
                  {% for error in field.errors %}
                    <p class="mt-3 text-danger">{{ error }}</p>
                  {% endfor %}
                </div>
              </div>
            </div>
          {% endfor %}
          {% csrf_token %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Sign in</button>
        </div>
      </form>
    </div>
  </div>
</div>

src/apps/user_auth/templates/user_auth/modals/sign_out.html
<div class="modal fade" id="logout_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Sign in form</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="alert alert-warning d-none" role="alert">
      </div>

      <form method="POST" action="{% url 'user_auth:logout' %}" id="logout_form">
        <div class="modal-body">
          Are you sure that you want to sign out ?
          {% csrf_token %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Sign out</button>
        </div>
      </form>
    </div>
  </div>
</div>